### ISSUE TITLE
Pixels around the output image may be black

### ISSUE THREAD

**Issue by splinter21** [andraantariksa/Anime4K-rs#1]

**Comment by randspace0** [comment]
Can you give me the example image (other than what I have provide)?

**Comment by splinter21** [comment]
![blur5_ani_1_d7_d12](https://user-images.githubusercontent.com/26759495/69214926-42696680-0ba3-11ea-8e76-35a90a18a559.png)
![blur5](https://user-images.githubusercontent.com/26759495/69214928-4301fd00-0ba3-11ea-9930-0d2c95ce53d4.png)

**Comment by splinter21** [comment]
img2:gt+blur5x5
img1:gt+blur5x5+anime4k_rust (black when x==0 or x==length_x-1 or y==0 or y==length_y-1)
